In [ ]:
! pip install numpy
! pip install opencv.python

! pip install matplotlib
import numpy as np
import random
import os
import cv2
import matplotlib.pyplot as plt
import pickle
import tensorflow as tf



In [ ]:
DIRECTORY='/content/drive/MyDrive/Category'
CATEGORIES=['CATS','DOGS']


In [ ]:
IMG_SIZE = 100
data = []

for category in CATEGORIES:
    folder = os.path.join(DIRECTORY, category)
    labels = CATEGORIES.index(category)
    for img in os.listdir(folder):
        img_path = os.path.join(folder, img)
        img_arr = cv2.imread(img_path)
        img_arr = cv2.resize(img_arr, (IMG_SIZE, IMG_SIZE))  # Resize the image
        img_arr = tf.convert_to_tensor(img_arr)  # Convert NumPy array to tensor
        data.append([img_arr, labels])



In [ ]:
len(data)

200

In [ ]:
random.shuffle(data)
data[0]


[<tf.Tensor: shape=(100, 100, 3), dtype=uint8, numpy=
 array([[[ 73,  82,  94],
         [ 83,  73,  82],
         [ 88, 108, 131],
         ...,
         [ 29,  41,  35],
         [ 17,  40,  32],
         [  3,  36,  29]],
 
        [[ 81,  85,  84],
         [ 97,  81,  68],
         [ 74,  85,  88],
         ...,
         [ 34,  48,  42],
         [ 29,  50,  42],
         [ 13,  48,  40]],
 
        [[108,  92,  70],
         [124,  95,  59],
         [ 65,  65,  55],
         ...,
         [ 38,  52,  46],
         [ 33,  49,  42],
         [  6,  40,  29]],
 
        ...,
 
        [[104, 115, 119],
         [103, 116, 119],
         [ 73,  84,  88],
         ...,
         [ 94, 107, 109],
         [104, 118, 117],
         [ 95, 107, 111]],
 
        [[ 64,  83,  90],
         [ 79,  88,  97],
         [ 66,  77,  85],
         ...,
         [109, 121, 127],
         [122, 140, 147],
         [101, 119, 126]],
 
        [[ 49,  74,  80],
         [ 74,  91,  98],
         [ 71,

In [ ]:
x=[]
y=[]
for features, labels in data:
  x.append(features)
  y.append(labels)



In [ ]:
x=np.array(x)
y=np.array(y)

pickle.dump(x, open('x.pkl', 'wb'))
pickle.dump(y, open('y.pkl', 'wb'))

In [ ]:
import pickle
pickle.load(open('x.pkl', 'rb'))
pickle.load(open('y.pkl', 'rb'))



array([1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1])

In [ ]:
x,y

(array([[[[ 73,  82,  94],
          [ 83,  73,  82],
          [ 88, 108, 131],
          ...,
          [ 29,  41,  35],
          [ 17,  40,  32],
          [  3,  36,  29]],
 
         [[ 81,  85,  84],
          [ 97,  81,  68],
          [ 74,  85,  88],
          ...,
          [ 34,  48,  42],
          [ 29,  50,  42],
          [ 13,  48,  40]],
 
         [[108,  92,  70],
          [124,  95,  59],
          [ 65,  65,  55],
          ...,
          [ 38,  52,  46],
          [ 33,  49,  42],
          [  6,  40,  29]],
 
         ...,
 
         [[104, 115, 119],
          [103, 116, 119],
          [ 73,  84,  88],
          ...,
          [ 94, 107, 109],
          [104, 118, 117],
          [ 95, 107, 111]],
 
         [[ 64,  83,  90],
          [ 79,  88,  97],
          [ 66,  77,  85],
          ...,
          [109, 121, 127],
          [122, 140, 147],
          [101, 119, 126]],
 
         [[ 49,  74,  80],
          [ 74,  91,  98],
          [ 71,  89,  96],
   

In [ ]:

y=y/255
x=x/255

In [ ]:
x.shape
y.shape


(200,)

In [ ]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

model = Sequential()

model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))


model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Flatten())


model.add(Dense(128, activation="relu"))
model.add(Dense(2, activation="softmax"))

model.compile(optimizer = 'adam', loss='sparse_categorical_crossentropy', metrics=["accuracy"])

model.fit(x,y, epochs=5, validation_split=0.1,)


Epoch 1/5
6/6 [==============================] - 6s 849ms/step - loss: 0.1261 - accuracy: 0.4500 - val_loss: 0.0000e+00 - val_accuracy: 0.5000
Epoch 2/5
6/6 [==============================] - 6s 988ms/step - loss: 0.0000e+00 - accuracy: 0.5000 - val_loss: 0.0000e+00 - val_accuracy: 0.5000
Epoch 3/5
6/6 [==============================] - 6s 846ms/step - loss: 0.0000e+00 - accuracy: 0.5000 - val_loss: 0.0000e+00 - val_accuracy: 0.5000
Epoch 4/5
6/6 [==============================] - 5s 825ms/step - loss: 0.0000e+00 - accuracy: 0.5000 - val_loss: 0.0000e+00 - val_accuracy: 0.5000
Epoch 5/5
6/6 [==============================] - 8s 1s/step - loss: 0.0000e+00 - accuracy: 0.5000 - val_loss: 0.0000e+00 - val_accuracy: 0.5000


In [ ]:
import pickle
import time
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.callbacks import TensorBoard

NAME=f'cat-vs-dog-prediction-{int(time.time())}'
tensoeboard=TensorBoard(log_dir=f'logs/')


x=pickle.load(open('x.pkl', 'rb'))
y=pickle.load(open('y.pkl', 'rb'))

x=x/255
y=y/255

model = Sequential()

model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))


model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Flatten())


model.add(Dense(128, activation="relu"))
model.add(Dense(2, activation="softmax"))

model.compile(optimizer = 'adam', loss='sparse_categorical_crossentropy', metrics=["accuracy"])

model.fit(x,y, epochs=5, validation_split=0.1, batch_size=32, callbacks=[tensoeboard])

Epoch 1/5
6/6 [==============================] - 7s 772ms/step - loss: 0.1360 - accuracy: 0.3944 - val_loss: 0.0000e+00 - val_accuracy: 0.5000
Epoch 2/5
6/6 [==============================] - 5s 762ms/step - loss: 0.0000e+00 - accuracy: 0.5000 - val_loss: 0.0000e+00 - val_accuracy: 0.5000
Epoch 3/5
6/6 [==============================] - 6s 1s/step - loss: 0.0000e+00 - accuracy: 0.5000 - val_loss: 0.0000e+00 - val_accuracy: 0.5000
Epoch 4/5
6/6 [==============================] - 4s 726ms/step - loss: 0.0000e+00 - accuracy: 0.5000 - val_loss: 0.0000e+00 - val_accuracy: 0.5000
Epoch 5/5
6/6 [==============================] - 4s 728ms/step - loss: 0.0000e+00 - accuracy: 0.5000 - val_loss: 0.0000e+00 - val_accuracy: 0.5000
